Add Makefile, configuration files and scripts
unikraft/app-httpreply pull request #14
Opened 2023-07-02 14:58 UTC by StefanJum

2023-07-02 21:13 UTC, razvand requested changes
See my comments?

2023-07-02 21:13 UTC, razvand commented on .gitignore
>  /a.out
Why are these here?

Ignore `build/`.

2023-07-02 21:13 UTC, razvand commented on README.md
> +$ apt-get install -y --no-install-recommends \
```suggestion
$ sudo apt install -y --no-install-recommends \
```

2023-07-02 21:13 UTC, razvand commented on README.md
> +     |   |-- lwip/
```suggestion
     |   `-- lwip/
```

2023-07-02 21:13 UTC, razvand commented on README.md
> +Connecting to 172.44.0.2:80... connected.
It's this port `8123`? Why port `80`?

2023-07-03 05:42 UTC, StefanJum commented
Done @razvand

2023-07-03 12:27 UTC, razvand approved these changes
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-07-03 12:50 UTC, closed without merging