Update README.md file with easier to use instructions
unikraft/app-httpreply pull request #15
Opened 2023-07-04 18:57 UTC by StefanJum

This will remove the running scripts and add the commands in the README file, rename the `config-*` files and add a `TLDR` section that summarises the setup.

2023-07-25 22:18 UTC, razvand requested changes
Hi, @StefanJum. Let's use the direct `qemu-system-...` command, not the full path.

Also, add back the `run-qemu-...` scripts that create the bridges behind the scenes.

2023-07-25 22:18 UTC, razvand commented on README.md
> +sudo /usr/bin/qemu-system-aarch64 \
```suggestion
sudo qemu-system-aarch64 \
```

2023-07-25 22:18 UTC, razvand commented on README.md
> +sudo /usr/bin/qemu-system-x86_64 \
```suggestion
sudo qemu-system-x86_64 \
```

2023-07-25 22:18 UTC, razvand commented on README.md
> +In order to run `nginx` you need to first set up a network bridge.
```suggestion
In order to run `httpreply` you need to first set up a network bridge.
```

2023-07-25 22:18 UTC, razvand commented on README.md
> +sudo /usr/bin/qemu-system-x86_64 \
```suggestion
sudo qemu-system-x86_64 \
```

2023-07-25 22:18 UTC, razvand commented on README.md
> +sudo /usr/bin/qemu-system-aarch64 \
```suggestion
sudo qemu-system-aarch64 \
```

2023-07-25 22:18 UTC, razvand commented on README.md
> +```console
This is too complicated. I say we re-add the `run-...` scripts. This is what we have for [`app-nginx`](https://github.com/unikraft/app-nginx), and I would keep it here. Makes it easier to test.

2023-07-26 08:02 UTC, StefanJum commented
Done @razvand

2023-07-26 15:10 UTC, razvand requested changes
@StefanJum, just some minor changes. Then we can approve it.

2023-07-26 15:10 UTC, razvand commented on .config.httpreply_qemu-arm64
> +CONFIG_UK_DEFNAME="httpreply"
```suggestion
CONFIG_UK_ARCH="arm64"
CONFIG_UK_DEFNAME="httpreply"
```

2023-07-26 15:10 UTC, razvand commented on .config.httpreply_qemu-x86_64
> +CONFIG_UK_DEFNAME="httpreply"
```suggestion
CONFIG_UK_ARCH="x86_64"
CONFIG_UK_DEFNAME="httpreply"
```

2023-07-26 15:24 UTC, StefanJum commented
Done @razvand

2023-07-30 14:41 UTC, razvand approved these changes
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-08-09 10:28 UTC, closed without merging