Bump Unikraft version to 0.10
unikraft/app-httpreply pull request #8
Opened 2022-08-26 10:44 UTC by eduardvintila

Signed-off-by: Eduard Vintilă <eduard.vintila47@gmail.com>

2022-08-26 12:03 UTC, StefanJum approved these changes
Works file, thank you!
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2022-08-28 15:25 UTC, razvand requested changes
Thanks, @eduardvintila . See my remarks.

2022-08-28 15:25 UTC, razvand commented on kraft.yaml
>  specification: '0.5'
```suggestion
---
specification: '0.5'
```

Compatible with the new syntax

2022-08-28 15:25 UTC, razvand commented on kraft.yaml
> +  version: '0.10.0'
```suggestion
  version: stable
```

2022-08-28 15:25 UTC, razvand commented on kraft.yaml
> +    version: '0.10.0'
```suggestion
    version: stable
```

2022-08-28 16:16 UTC, razvand approved these changes
This works. Thanks, @eduardvintila 

Reviewed-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>
Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

2022-08-29 11:33 UTC, closed without merging